export { default as Header } from "./header/Header";
export { default as HeaderDefault} from "./headerDefault/HeaderDefault";
export { default as Button } from "./button/Button"; 
export {default as About} from "./about/About";
export {default as DividerTop} from "./divider/DividerTop";
export {default as DividerBottom} from "./divider/DividerBottom";
export {default as DividerTiltTop} from "./divider/DividerTiltTop";
export {default as DividerTiltBottom} from "./divider/DividerTiltBottom";
export { default as Depositions } from "./depositions/Depositions";
export { default as Details} from "./details/Details";
export { default as Subjects} from "./subjects/Subjects";
export {default as Bonus} from "./bonus/Bonus";
export { default as FreeClass } from "./freeClass/FreeClass";
export {default as SocialProof} from "./socialProof/SocialProof";
export {default as Certificates} from "./certificates/Certificates";
export{default as LifeTimeAccess} from "./lifeTimeAccess/LifeTimeAccess";
export{default as Garantee} from "./guarantee/Guarantee";
export{default as SmallWave} from "./smallWave/SmallWave";
export{default as Promotion} from "./promotion/Promotion";
export{default as WavesDividerTop} from "./wavesDivider/WavesDividerTop";
export{default as WavesDividerBottom} from "./wavesDivider/WavesDividerBottom";
export { default as ButtonHome } from "./buttonHome/ButtonHome";
export{default as Footer} from "./footer/Footer";
export{default as Modal} from "./modal/Modal";