export { default as Header } from "./header/Header";
export { default as Button } from "./button/Button"; 
export { default as Waves} from "./waves/Waves";
export {default as About} from "./about/About";
export {default as Divider} from "./divider/Divider";
export { default as Depositions } from "./depositions/Depositions";
export { default as Details} from "./details/Details";
export { default as Subjects} from "./subjects/Subjects";
export {default as Bonus} from "./bonus/Bonus";
export { default as FreeClass } from "./freeClass/FreeClass";
export {default as SocialProof} from "./socialProof/SocialProof";